// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0zJov6gr7GNy7xwUlP81UaO8WJtD6TY',
    appId: '1:653010187544:web:2b2c919a07b2f12f491a6d',
    messagingSenderId: '653010187544',
    projectId: 'score-manager1',
    authDomain: 'score-manager1.firebaseapp.com',
    storageBucket: 'score-manager1.appspot.com',
    measurementId: 'G-VRVQ7ESKNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiAUdwwOOkKdCQBZEW7L30XPanyUF2eY',
    appId: '1:653010187544:android:43ed604b6bfe95b0491a6d',
    messagingSenderId: '653010187544',
    projectId: 'score-manager1',
    storageBucket: 'score-manager1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPRGVw6GrtH-3pPAtoDznLb6QyWn94y0',
    appId: '1:653010187544:ios:ddf7566be63a7389491a6d',
    messagingSenderId: '653010187544',
    projectId: 'score-manager1',
    storageBucket: 'score-manager1.appspot.com',
    iosBundleId: 'com.techNova.scoremanager.scoreManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPRGVw6GrtH-3pPAtoDznLb6QyWn94y0',
    appId: '1:653010187544:ios:dcc029edc6c9a601491a6d',
    messagingSenderId: '653010187544',
    projectId: 'score-manager1',
    storageBucket: 'score-manager1.appspot.com',
    iosBundleId: 'com.techNova.scoremanager.scoreManager.RunnerTests',
  );
}
